config/routes.rb
Rails.application.routes.draw do
  get '/home/about' => 'home#about'
  get 'users/followings/:follow_id' => 'users#followings',as: 'user_followings'
  get 'users/followers/:follow_id' => 'users#followers',as: 'user_followers'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root 'posts#top'
  resources :users, only: [:index, :show, :new, :edit, :create, :update, :new]
  resources :posts, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resources :post_comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
	belongs_to :follow, class_name: 'User'

	validates :user_id, presence: true
	validates :follow_id, presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_action :set_user
	before_action :authenticate_user!

	def create
		following = current_user.follow(@user)
		if following.save
			redirect_back(fallback_location: root_path)
		else
			redirect_back(fallback_location: root_path)
		end
	end

	def destroy
		following = current_user.unfollow(@user)
		if following.destroy
			redirect_back(fallback_location: root_path)
		else
			redirect_back(fallback_location: root_path)
		end
	end

	private
	def set_user
		@user = User.find(params[:relationship][:follow_id])
	end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <div class="follower-btn">
      <%= form_with(model: @relationship, url: relationship_path(user), method: :delete, remote: true) do |f| %>
        <%= f.hidden_field :follow_id, value: user.id %>
        <%= button_tag '<i class="fas fa-user-check"><div class="follower-push">フォロー中</div></i>'.html_safe, :type => "submit", class: "btn btn--red" %>
      <% end %>
    </div>
  <% else %>
    <div class="follow-btn">
      <%= form_with(model: @set_relationship, url: relationships_path, remote: true) do |f| %>
        <%= f.hidden_field :follow_id, value: user.id %>
        <%= button_tag '<i class="fas fa-user-plus"><div class="follow-push">フォローする</div></i>'.html_safe, :type => "submit", class: "btn btn--blue" %>
      <% end %>
   <% end %>
<% end %>

app/views/relationships/create.js.erb
$("#relationships_buttons_<%= @user.id %>").html("<%= j(render partial: 'relationships/follow_button', locals: {user: @user}) %>");
// $("#follower-count_<%= @user.id %>").html('<%= link_to "#{ @user.followers.count }フォロワー", user_followers_path(@user) %>');
// $("#following-count_<%= current_user.id %>").html('<%= link_to "#{ current_user.followings.count }フォロー", user_followings_path(@user) %>');

app/views/relationships/destroy.js.erb
$("#relationships_buttons_<%= @user.id %>").html("<%= j(render partial: 'relationships/follow_button', locals: {user: @user}) %>");
// $("#follower-count_<%= @user.id %>").html('<%= link_to "#{ @user.followers.count }フォロワー", user_followers_path(@user) %>');
// $("#following-count_<%= current_user.id %>").html('<%= link_to "#{ current_user.followings.count }フォロー中", user_followings_path(@user) %>');