config/routes.rb
Rails.application.routes.draw do
  get '/home/about' => 'home#about'
  get 'users/followings/:follow_id' => 'users#followings',as: 'user_followings'
  get 'users/followers/:follow_id' => 'users#followers',as: 'user_followers'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root 'posts#top'
  resources :users, only: [:index, :show, :new, :edit, :create, :update, :new]
  resources :posts, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resources :post_comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

	belongs_to :user
	belongs_to :post
	validates :comment, presence: true
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
	before_action :authenticate_user!

	def create
		post = Post.find(params[:post_id])
		comment = current_user.post_comments.new(post_comment_params)
		comment.post_id = post.id
		comment.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		PostComment.find_by(id: params[:id], post_id: params[:post_id]).destroy
		redirect_back(fallback_location: root_path)
	end

	private
  	def post_comment_params
    	params.require(:post_comment).permit(:comment)
  	end

end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/post_comments/_comments.html.erb
<div class="comment-all">
	<% @post.post_comments.each do |post_comment| %>
	    	<div class="comment-text">
	      		<div class="comment-body bb">
	        		<div class="comment-avatar clearfix">
	          			<div class="avatar">
	          				<%= link_to user_path(post_comment.user), remote: true do %>
	            				<%= attachment_image_tag post_comment.user, :profile_image, :fill, 60, 60, class: "img-circle" %>
	            			<% end %>
	          			</div>
		          			<div class="comment">
		          				<%= post_comment.comment %>
		          			</div>
			          			<% if post_comment.user == current_user %>
			          			<div class="comment-delete">
			          				<div class="delete-btn">
			              			<%= link_to "削除", post_post_comment_path(post_comment.post, post_comment), method: :delete, remote: true, class: "text-muted" %>
			              			</div>
			              		</div>
								<% end %>
	        		</div>
	        		<div class="comment-area">
	          			<div class="comment-author clearfix">
	            			<strong> <%= post_comment.user.name %> </strong>
	          			</div>
						<div class="day">
							<%= l @post.created_at, format: :long %>
						</div>
	       			</div>
	      		</div>
	    	</div>
	 	<% end %>
</div>

app/views/post_comments/create.js.erb
$("#comment-<%= @post_comment.id %>").html("<%= j(render partial: 'post_comments/comments', locals: {post_comment: @post_comment, post: @post}) %>");
$("text_area").val('')

app/views/post_comments/destroy.js.erb
$("#comment-<%= @post_comment.id %>").html("<%= j(render partial: 'post_comments/comments', locals: {post_comment: @post_comment, post: @post}) %>");
$("text_area").val('')