config/routes.rb
Rails.application.routes.draw do
  get '/home/about' => 'home#about'
  get 'users/followings/:follow_id' => 'users#followings',as: 'user_followings'
  get 'users/followers/:follow_id' => 'users#followers',as: 'user_followers'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root 'posts#top'
  resources :users, only: [:index, :show, :new, :edit, :create, :update, :new]
  resources :posts, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resources :post_comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  has_many :relationships, foreign_key: "user_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def self.guest
    find_or_create_by!(email: 'gest@.com', name: 'ゲスト') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :index, :show]
  before_action :ensure_correct_user, only: [:update, :edit]

  def index
    @users = User.all.order(created_at: :desc)
    @users = @users.where('name LIKE ? OR introduction LIKE ?', "%#{params[:search]}%","%#{params[:search]}%") if params[:search].present?
    @relationship = current_user.relationships.find_by(follow_id: @users.ids)
    @set_relationship = current_user.relationships.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
    @post = Post.new
    @relationship = current_user.relationships.find_by(follow_id: @user.id)
    @set_relationship = current_user.relationships.new
  end

  def followings
    @user = User.find(params[:follow_id])
    @users = @user.followings.all.order(created_at: :desc)
    @relationship = current_user.relationships.find_by(follow_id: @user.id)
    @set_relationship = current_user.relationships.new
  end

  def followers
    @user = User.find(params[:follow_id])
    @users = @user.followers.all.order(created_at: :desc)
    @relationship = current_user.relationships.find_by(follow_id: @user.id)
    @set_relationship = current_user.relationships.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :gender)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<% @users.each do |user| %>
	<div class="user-index clearfix">
		<table>
			<div class="user-index-text">
				<tbody>
					<tr>
						<td class="user-index-image">
							<%= link_to user_path(user) do %>
								<%= attachment_image_tag(user, :profile_image, :fill, 150, 150, class: "img-circle") %>
							<% end %>
						</td>
						<td class="user-index-user-name">
							<strong> <%= user.name %> </strong>
						</td>
						<td class="user-index-user-gender">
							<%= user.gender %>
						</td>
						<td class="user-index-user-followers">
							<%= link_to user_followings_path(user) do %>
								<div class="follow">フォロー
									<%= user.followings.count %>
								</div>
							<% end %>
							<%= link_to user_followers_path(user) do %>
								<div class="followers"> フォロワー
									<%= user.followers.count %>
								</div>
							<%  end %>
						</td>
					</tr>
				</tbody>
			</div>
		</table>
	</div>
<% end %>

app/views/users/edit.html.erb
<div class="edit">
<h1>プロフィール編集</h1>

<%= form_with(model: @user, local: true) do |f| %>
	<!-- エラー文 -->
	<% if @user.errors.any? %>
		<div id="error_explanation" class="alert alert-danger">
			<h3><%= I18n.t("errors.messages.not_saved",
	                 count: @user.errors.count,
	                 resource: @user.class.model_name.human.downcase) %>
	       </h3>
				<ul>
				<% @user.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
				</ul>
		</div>
	<% end %>
	<!-- エラー文 -->
	<div class="edit-text">
		<table class="edit-table">
			<tbody>
				<tr>
					<td class="field">
						<div class="edit-plofile">
							<%= f.label :プロフィール画像 %>
						</div>
						<div class="edit-image">
							<%= f.attachment_field :profile_image %>
						</div>
					</td>
				</tr>
				<tr>
					<td class="field">
						<div class="edit-plofile">
							<%= f.label :名前又はニックネーム %>
						</div>
						<div class="edit-name">
							<%= f.text_field :name %>
						</div>
					</td>
				</tr>
				<tr>
					<td class="field">
						<div class="edit-plofile">
							<%= f.label :性別 %>
						</div>
						<div class="edit-gender">
							<div class="men">
								<%= f.radio_button :gender, "MEN" %>MEN
							</div>
							<div class="women">
								<%= f.radio_button :gender, "WOMEN" %>WOMEN
							</div>
						</div>
					</td>
				</tr>
				<tr>
					<td class="field">
						<div class="edit-plofile">
							<%= f.label :自己紹介 %>
						</div>
						<div class="edit-introduction">
							<%= f.text_area :introduction, :size=>"40" %>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
			<div class="edit-btn">
				<%= f.submit "変更する", class: "btn btn--edit-gray btn--cubic" %>
			</div>
	</div>
<% end %>
</div>

app/views/users/followers.html.erb
<div class="text">
<h2>フォロワー一覧</h2>
	<%= render partial: 'follow', locals: { user: @user } %>
</div>

app/views/users/followings.html.erb
<div class="text">
<h2>フォロー一覧</h2>
	<%= render partial: 'follow', locals: { user: @user } %>
</div>

app/views/users/index.html.erb
<div class="text">
<h1>ユーザー一覧</h1>
<!-- 検索バー -->
<div class="search">
	<%= form_with url: users_path, method: :get, local: true do |f| %>
	  <%= f.text_field :search, placeholder: "キーワード検索" %>
	  <%= button_tag '<i class="fas fa-search"></i>'.html_safe, :type => "submit" %>
	<% end %>
</div>
<!-- 検索バー -->
	<% @users.each do |user| %>
		<div class="user-index clearfix">
			<table>
				<div class="user-index-text">
					<tbody>
						<tr>
							<td class="user-index-image">
								<%= link_to user_path(user) do %>
									<%= attachment_image_tag(user, :profile_image, :fill, 150, 150,  class: "img-circle") %>
								<% end %>
							</td>
							<td class="user-index-user-name">
								<%= link_to user_path(user) do %>
									<strong class="name-color"> <%= user.name %> </strong>
								<% end %>
							</td>
							<td class="user-index-user-gender">
								<%= user.gender %>
							</td>
							<td class="user-index-user-followers">
								<%= link_to user_followers_path(user) do %>
									<div class="followers"> フォロワー
										<%= user.followers.count %>
									</div>
								<%  end %>
							</td>
						    <td class="user-index-follow">
						      	<div id="relationships_buttons_<%= user.id %>">
								    <%= render partial: 'relationships/follow_button', locals: {user: user} %>
								</div>
						    </td>
						</tr>
					</tbody>
				</div>
			</table>
		</div>
	<% end %>
</div>

app/views/users/show.html.erb
<div class="text">
	<!-- ユーザー詳細 -->
	<div class="my-page ">
		<div class="plofile clearfix">
			<div class="user-image">
				<%= attachment_image_tag @user, :profile_image, :fill, 180, 180, class: "img-circle" %>
			</div>
			<div class="plofile-text">
				<div class="user-introduction">
					<div class="name">
						<strong> <%= @user.name %> </strong>
					</div>
					<div class="gender">
						<%= @user.gender %>
					</div>
					<div class="introduction">
						<%= @user.introduction %>
					</div>
				</div>
				<div class="follow-text">
					<%= link_to user_followings_path(@user) do %>
						<div class="follow"> フォロー
							<%= @user.followings.count %>
						</div>
						<% end %>
					<%= link_to user_followers_path(@user) do %>
						<div class="followers"> フォロワー
							<%= @user.followers.count %>
						</div>
					<%  end %>
				</div>
			</div>

			<div class="follow-btn">
				<div id="relationships_buttons_<%= @user.id %>">
					<%= render partial: 'relationships/follow_button', locals: {user: @user} %>
				</div>
			</div>

			<% if @user == current_user %>
				<div class="user-post-profiel">
					<div class="plofile-btn clearfix">
						<%= link_to "プロフィール変更", edit_user_path, class: "btn btn--gray btn--cubic" %>
					</div>
					<div class="new-post">
						<%= link_to "投稿する", new_post_path, class: "btn btn--black btn--cubic" %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
	<!-- ユーザー詳細 -->

	<!-- ユーザー投稿一覧 -->
	<div class="user-post-all">
		<h2 class="user-post-main">〜写真一覧〜</h2>
		<div class="user-post">
			<% @posts.each do |post| %>
				<div class="post-index-image">
					<div class="solid">
						<%= link_to post_path(post) do %>
							<%= attachment_image_tag(post, :post_image, :fill, 250, 300, class: "img-rounded") %>
						<% end %>
						<div class="post-index-title">
							<%= link_to post_path(post) do %>
							<div class="post-title">
								<strong class="user-post-title"> <%= post.title %> </strong>
							</div>
							<% end %>
							<div class="post-time">
								<%= l post.created_at, format: :long %>
							</div>
							<div class="user-index-favorite">
								<div id="favorites_buttons_<%= post.id %>">
									<%= render partial: 'favorites/favorite', locals: {post: post} %>
								</div>
							</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
	<!-- ユーザー投稿一覧 -->
	<!-- いいね一覧 -->
	<div class="user-post-all">
		<h2 class="user-post-main">〜いいね一覧〜</h2>
			<div class="user-post">
				<% @user.favorite_posts.each do |post| %>
					<div class="post-index-image">
						<div class="solid">
							<%= link_to post_path(post) do %>
								<%= attachment_image_tag(post, :post_image, :fill, 250, 300, class: "img-rounded") %>
							<% end %>
							<div class="post-index-title">
								<%= link_to post_path(post) do %>
								<div class="post-title">
									<strong class="user-post-title"> <%= post.title %> </strong>
								</div>
								<% end %>
								<div class="post-time">
									<%= l post.created_at, format: :long %>
								</div>
								<div class="user-index-favorite">
									<div id="favorites_buttons_<%= post.id %>">
										<%= render partial: 'favorites/favorite', locals: {post: post} %>
									</div>
								</div>
							</div>
						</div>
					</div>
				<% end %>
			</div>
	</div>
	<!-- いいね一覧 -->
</div>