config/routes.rb
Rails.application.routes.draw do
  get '/home/about' => 'home#about'
  get 'users/followings/:follow_id' => 'users#followings',as: 'user_followings'
  get 'users/followers/:follow_id' => 'users#followers',as: 'user_followers'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root 'posts#top'
  resources :users, only: [:index, :show, :new, :edit, :create, :update, :new]
  resources :posts, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resources :post_comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
  validates :post_image, presence: true

	belongs_to :user
	attachment :post_image
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
  has_many :tags, dependent: :destroy

	def favorited_by?(user)
    	favorites.where(user_id: user.id).exists?
  end

  def self.create_favorite_ranks
  	Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
  end

  def self.create_relationship_ranks
  	User.find(Relationship.group(:follow_id).order('count(follow_id) desc').limit(3).pluck(:follow_id))
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: [:edit, :new, :show, :create, :index]
  before_action :correct_user, only: [:update, :edit]

  def top
    @favorite_ranks = Post.create_favorite_ranks
    @relationship_ranks = Post.create_relationship_ranks
  end


  def index
  	@posts = Post.all.order(created_at: :desc)
    @post = Post.new
    @user = current_user
    @posts = @posts.where('title LIKE ? OR body LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
  	@post = Post.find(params[:id])
  	@user = @post.user
    @post_comment = PostComment.new
    @relationship = current_user.relationships.find_by(follow_id: @user.id)
    @set_relationship = current_user.relationships.new
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)
  	@post.user = current_user
  	if @post.save
      tags = Vision.get_image_data(@post.post_image)
      tags.each do |tag|
        @post.tags.create(name: tag)
      end
  	  redirect_to post_path(@post)
    else
      render :new
    end
  end

  def update
    @user = current_user
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @user = current_user
    @post.destroy
    redirect_to user_path(@user)
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :post_image, :user_id)
  end

  def correct_user
    post = Post.find(params[:id])
    if current_user != post.user
      redirect_to root_path
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>
	<!-- エラー文 -->
	<% if @post.errors.any? %>
		<div id="error_explanation" class="alert alert-danger">
			<h3><%= I18n.t("errors.messages.not_saved",
	                 count: @post.errors.count,
	                 resource: @post.class.model_name.human.downcase) %>
	        </h3>
				<ul>
				<% @post.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
				</ul>
		</div>
	<% end %>
	<!-- エラー文 -->
	<div class="edit-text">
		<table class="edit-table">
			<tbody>
				<tr>
					<td class="field">
						<div class="edit-plofile">
							<%= f.label :写真 %>
						</div>
						<div class="edit-image">
							<%= f.attachment_field :post_image %>
						</div>
					</td>
				</tr>
				<tr>
					<td class="field">
						<div class="edit-plofile">
							<%= f.label :タイトル %>
						</div>
						<div class="edit-name">
							<%= f.text_field :title %>
						</div>
					</td>
				</tr>
				<tr>
					<td class="field">
						<div class="edit-plofile">
							<%= f.label :説明文 %>
						</div>
						<div class="edit-introduction">
							<%= f.text_area :body, :size=>"40" %>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
			<div class="edit-btn">
				<%= f.submit "投稿", class: "btn btn--black btn--cubic" %>
			</div>
	</div>
<% end %>

app/views/posts/edit.html.erb
<div class="edit">
<h2>編集画面</h2>
	<%= render partial: 'form', locals: { post: @post } %>
</div>

app/views/posts/index.html.erb
<div class="text">
<h1>写真一覧</h1>
<!-- 検索バー -->
<div class="search">
	<%= form_with url: posts_path, method: :get, local: true do |f| %>
	  	<%= f.text_field :search, placeholder: "キーワード検索" %>
	  	<%= button_tag '<i class="fas fa-search"></i>'.html_safe, :type => "submit" %>
	<% end %>
</div>
<!-- 検索バー -->
	<div class="user-post">
		<% @posts.each do |post| %>
			<div class="post-index-image">
				<div class="solid">
					<%= link_to post_path(post) do %>
						<%= attachment_image_tag(post, :post_image, :fill, 250, 350, class: "img-rounded") %>
					<% end %>
					<div class="post-index-title">
						<%= link_to post_path(post) do %>
							<div class="post-title">
								<strong class="user-post-title"> <%= post.title %> </strong>
							</div>
						<% end %>
						<div class="post-solid">
							<%= link_to user_path(post.user) do %>
								<div class="post-user-image">
									<%= attachment_image_tag(post.user, :profile_image, :fill, 50, 50,) %>
								</div>
							<% end %>
							<div class="post-index-name">
								<%= link_to user_path(post.user) do %>
									<strong class="name-color"> <%= post.user.name %> </strong>
								<% end %>
							</div>
							<div class="post-index-favorite clearfix">
								<div id="favorites_buttons_<%= post.id %>">
									<%= render partial: 'favorites/favorite', locals: {post: post} %>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/posts/new.html.erb
<div class="edit">
<h2>投稿画面</h2>
	<%= render partial: 'form', locals: { post: @post } %>
</div>

app/views/posts/show.html.erb
<div class="text">
	<!-- ユーザー -->
	<div class="user-index clearfix">
		<table>
			<div class="user-index-text">
				<tbody>
					<tr>
						<td class="user-index-image">
							<%= link_to user_path(@user) do %>
								<%= attachment_image_tag(@user, :profile_image, :fill, 150, 150, class: "img-circle") %>
							<% end %>
						</td>
						<td class="user-index-user-name">
							<strong> <%= @user.name %> </strong>
						</td>
						<td class="user-index-user-gender">
							<%= @user.gender %>
						</td>
						<td class="user-index-user-followers">
							<%= link_to user_followers_path(@user) do %>
								<div class="followers"> フォロワー
									<%= @user.followers.count %>
								</div>
							<%  end %>
						</td>
					    <td class="user-index-follow">
					      	<div id="relationships_buttons_<%= @user.id %>">
							    <%= render partial: 'relationships/follow_button', locals: {user: @user} %>
							</div>
					    </td>
					</tr>
				</tbody>
			</div>
		</table>
	</div>
	<!-- ユーザー -->
	<!-- 投稿詳細 -->
	<div class="post-show-main clearfix">
		<div class="post-show-post-image">
			<%= attachment_image_tag @post, :post_image, :fill, 550, 750, class: "img-rounded" %>
		</div>
			<div class="post-show-post">
				<div class="post-show-post-text">
					<div class="post-show-post-title">
						<strong>〜 <%= @post.title %> 〜</strong>
					</div>
					<div class="post-show-post-body">
						<%= @post.body %>
					</div>
					<div class="post-day">
						<%= l @post.created_at, format: :long %>
					</div>
					<div class="post-show-favorites">
						<div id="favorites_buttons_<%= @post.id %>">
									<%= render partial: 'favorites/favorite', locals: {post: @post} %>
						</div>
					</div>
					<div class="post-show-edit">
						<% if @user == current_user %>
							<%= link_to "編集", edit_post_path(@post), class: "text-muted" %>
							<%= link_to "削除", post_path(@post), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "text-muted" %>
						<% end %>
					</div>
				</div>
			</div>
	</div>
	<!-- 投稿詳細 -->
	<div class="api">
		<% @post.tags.each do |tag| %>
			<div class="api_name"> <%= tag.name %> </div>
		<% end %>
	</div>
	<!-- コメント -->
	<div class="comment-title">
		<strong> コメント： <%= @post.post_comments.count %>件 </strong>
	</div>
		<div id="comment-<%= @post_comment.id %>">
			<%= render partial: 'post_comments/comments', locals: {post_comment: @post_comment, post: @post} %>
		</div>
			<% unless @user == current_user %>
				<%= form_with(model: [@post, @post_comment], remote: true) do |f| %>
					<div class="row">
						<div class="col-sm-8">
							<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
							<%= f.submit "送信", class: "btn btn--black btn--cubic pull-right" %>
						</div>
					</div>
				<% end %>
			<% end %>
	<!-- コメント -->
</div>

app/views/posts/top.html.erb
<div class="top-image">
	<p class="top-title">Faashion Snap</p>
</div>

<div class="top-main">
	<div class="top-main-text">
		<div class="top-ranking">
			<h1 class="ranking"> <strong>☆RANKING☆</strong> </h1>
		</div>
		<!-- いいねランキング -->
			<div class="top-favorite">
				<h2>〜いいね数〜</h2>
			</div>
				<% lastfavorite = 0 %>
				<% j = 1 %>
				<div class="top-user-post">
					<% @favorite_ranks.each.with_index(1) do |post, i| %>
						<% if i == 1 %>
							<% lastfavorite = post.favorites.count %>
						<% end %>
							<% if post.favorites.count != lastfavorite %>
								<% j = i %>
								<div class="post-index-image">
									<div class="top-favorite-ranking-text clearfix">
										<div class="top-ranking-count">
											第<%= j %>位
										</div>
										<div class="top-favorite-count">
											<%= post.favorites.count %> いいね
										</div>
									</div>
									<div class="solid">
										<div class="top-post-image">
											<%= link_to post_path(post) do %>
												<%= attachment_image_tag(post, :post_image, :fill, 250, 350, class: "img-rounded") %>
											<% end %>
										</div>
										<div class="top-post-title">
											<%= link_to post_path(post) do %>
												<strong class="user-post-title"> <%= post.title %> </strong>
											<% end %>
										</div>
									</div>
								</div>
								<% lastfavorite = post.favorites.count %>
							<% else %>
								<% lastfavorite = post.favorites.count %>
								<div class="post-index-image">
									<div class="top-favorite-ranking-text clearfix">
										<div class="top-ranking-count">
											第<%= j %>位
										</div>
										<div class="top-favorite-count">
											<%= post.favorites.count %> いいね
										</div>
									</div>
									<div class="solid">
										<div class="top-post-image">
											<%= link_to post_path(post) do %>
												<%= attachment_image_tag(post, :post_image, :fill, 250, 350, class: "img-rounded") %>
											<% end %>
										</div>
										<div class="top-post-title">
											<%= link_to post_path(post) do %>
												<strong class="user-post-title"> <%= post.title %> </strong>
											<% end %>
										</div>
									</div>
								</div>
							<% end %>
						<% end %>
				</div>
				<div class="more">
					<div class="more-text">
						<%= link_to "＜投稿をもっと見る＞", posts_path, class: "text-muted" %>
					</div>
				</div>
	</div>
	<!-- いいねランキング -->
	<!-- フォロワーランキング -->
	<div class="top-main-text">
		<div class="top-follow">
			<h2>〜フォロワー数〜</h2>
		</div>
		<% lastrelationship = 0 %>
		<% j = 1 %>
		<div class="top-user">
			<% @relationship_ranks.each.with_index(1) do |user, i| %>
				<% if i == 1 %>
					<% relationship = user.followers.count %>
				<% end %>
				<% if user.followers.count != lastrelationship %>
					<% j = i %>
					<div class="top-follow-ranking">
						<div class="clearfix">
							<div class="top-ranking-count">
								第<%= j %>位
							</div>
							<div class="top-relationship">
								フォロワー <%= user.followers.count %> 人
							</div>
						</div>
						<div class="top-post-image-follower">
							<%= link_to user_path(user) do %>
								<%= attachment_image_tag(user, :profile_image, :fill, 180, 180, class: "img-circle") %>
							<% end %>
						</div>
						<div class="top-user-name">
							<%= link_to user_path(user) do %>
								<strong class="user-name"> <%= user.name %> </strong>
							<% end %>
						</div>
					</div>
					<% lastrelationship = user.followers.count %>
				<% else %>
					<% lastrelationship = user.followers.count %>
					<div class="top-follow-ranking">
						<div class="clearfix">
							<div class="top-ranking-count">
								第<%= j %>位
							</div>
							<div class="top-relationship">
								フォロワー <%= user.followers.count %> 人
							</div>
						</div>
						<div class="">
							<%= link_to user_path(user) do %>
							<%= attachment_image_tag(user, :profile_image, :fill, 180, 180, class: "img-circle") %>
							<% end %>
						</div>
						<div class="top-user-name">
							<%= link_to user_path(user) do %>
								<strong class="user-name"> <%= user.name %> </strong>
							<% end %>
						</div>
					</div>
				<% end %>
			<% end %>
		</div>
		<div class="more">
			<div class="more-text">
				<%= link_to "＜ユーザーをもっと見る＞", users_path, class: "text-muted" %>
			</div>
		</div>
	</div>
	<!-- フォロワーランキング -->
</div>